{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.shushant.kourier",
    "module": "kourier-core",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-core-metadata-0.0.1.jar",
          "url": "kourier-core-0.0.1.jar",
          "size": 24615,
          "sha512": "c8a9802c2933e143f61eba3728079da86ac907be7b4f70785fe47736f39f2e5c55978f545717f5f8864a24751bec7f228655fdaa8752d9b62830cfb600966f2e",
          "sha256": "1056ff730c404a30527d5d61317a40ebbb70b51060e91804fe2024b2a56d6cfd",
          "sha1": "16dab4a46d9d96206e98677385632334d6c6b90d",
          "md5": "1cc92e4ff4bc5ba5be2b36c6a850ceab"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kourier-core-kotlin-0.0.1-sources.jar",
          "url": "kourier-core-0.0.1-sources.jar",
          "size": 22096,
          "sha512": "862db9930036992cc329dc64e603160f3a0e8be91851d8e566ed8db8733b2fd9c34407dcfc4a3be7cf9078e1d5ed1f2e788b9e4a6260778d51863615ffc5b3f7",
          "sha256": "82fb878ee3fb8d7c4b3b22eab415e9dde0810089d58560f90b657b2da403e295",
          "sha1": "53b4dd56cdf8a9eeea663b19b90e2dcdfdc2b622",
          "md5": "25ac04d040d64e3856fc24bb6dba57cc"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-core-android/0.0.1/kourier-core-android-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-core-android/0.0.1/kourier-core-android-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-core-android/0.0.1/kourier-core-android-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iosarm64/0.0.1/kourier-core-iosarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iosarm64/0.0.1/kourier-core-iosarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iosarm64/0.0.1/kourier-core-iosarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iossimulatorarm64/0.0.1/kourier-core-iossimulatorarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iossimulatorarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iossimulatorarm64/0.0.1/kourier-core-iossimulatorarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iossimulatorarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iossimulatorarm64/0.0.1/kourier-core-iossimulatorarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iossimulatorarm64",
        "version": "0.0.1"
      }
    }
  ]
}
